# Generated by Django 3.1.7 on 2021-04-07 00:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('startingPrice', models.DecimalField(decimal_places=2, max_digits=9)),
                ('auctionStarts', models.DateTimeField(auto_now_add=True)),
                ('auctionEnds', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=400)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ManyToManyField(related_name='comment', to='auctions.AuctionListing')),
                ('author', models.ManyToManyField(related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ManyToManyField(related_name='offers', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ManyToManyField(related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
