# Generated by Django 3.1.7 on 2021-04-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='startingPrice',
            new_name='Starting Price',
        ),
    ]
