# Generated by Django 3.1.7 on 2021-04-07 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210406_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='auctionEnds',
            new_name='Duration',
        ),
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='auctionStarts',
            new_name='Starts',
        ),
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='title',
            new_name='Title',
        ),
    ]
