# Generated by Django 3.1.7 on 2021-04-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210406_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='Duration',
            field=models.DateTimeField(editable=False),
        ),
    ]
