# Generated by Django 3.1.7 on 2021-04-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210416_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='Duration',
            new_name='Ends',
        ),
    ]
