# Generated by Django 3.1.7 on 2021-04-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210418_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='Ends',
            field=models.DateTimeField(),
        ),
    ]
