# Generated by Django 3.1.7 on 2021-04-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210418_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='img',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
