# Generated by Django 3.1.7 on 2021-04-29 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210420_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='seller',
            new_name='auctioneer',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='auctioneer',
            field=models.ManyToManyField(related_name='auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
