# Generated by Django 3.1.7 on 2021-04-29 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210429_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auctioneer',
        ),
        migrations.AlterField(
            model_name='bid',
            name='buyer',
            field=models.ManyToManyField(related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
