# Generated by Django 3.1.7 on 2021-04-29 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210429_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ManyToManyField(editable=False, related_name='bid', to='auctions.AuctionListing'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='buyer',
            field=models.ManyToManyField(editable=False, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
